# Generated by Django 5.0 on 2023-12-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todolists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_task', models.CharField(max_length=100, verbose_name='Что нужно сделать: ')),
                ('if_complete', models.BooleanField(verbose_name='Сделано или нет')),
            ],
        ),
    ]
