# Generated by Django 5.0 on 2023-12-25 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolists',
            options={'verbose_name': 'Список дел', 'verbose_name_plural': 'Список дел'},
        ),
        migrations.RenameField(
            model_name='todolists',
            old_name='if_complete',
            new_name='done_or_not',
        ),
    ]
