# Generated by Django 5.0 on 2024-01-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_todolists_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='todolists',
            name='list_of_tasks',
            field=models.ManyToManyField(to='todolist.listoftodolist'),
        ),
    ]
