# Generated by Django 5.0 on 2024-01-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_listoftodolist_todolists_list_of_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolists',
            name='list_of_tasks',
        ),
        migrations.RenameModel(
            old_name='ListOfToDoList',
            new_name='ValueModel',
        ),
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('values', models.ManyToManyField(to='todolist.valuemodel')),
            ],
        ),
    ]
