# Generated by Django 5.0 on 2024-01-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_remove_todolists_list_of_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolists',
            name='values',
            field=models.ManyToManyField(blank=True, null=True, related_name='test_list', to='todolist.valuemodel'),
        ),
        migrations.DeleteModel(
            name='ListModel',
        ),
    ]
