# Generated by Django 5.0 on 2024-01-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_todolists_values_delete_listmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolists',
            old_name='values',
            new_name='list_of_todos',
        ),
    ]
