# Generated by Django 5.0 on 2024-01-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_rename_values_todolists_list_of_todos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfToDos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_task', models.CharField(max_length=100, verbose_name='Что нужно сделать: ')),
                ('done_or_not', models.BooleanField(verbose_name='Сделано или нет')),
            ],
        ),
        migrations.DeleteModel(
            name='ValueModel',
        ),
        migrations.AlterField(
            model_name='todolists',
            name='list_of_todos',
            field=models.ManyToManyField(blank=True, null=True, related_name='test_list', to='todolist.listoftodos'),
        ),
    ]
