# Generated by Django 5.0 on 2024-01-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_remove_todolists_list_of_todos_delete_listoftodos'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolists',
            name='task_data',
            field=models.JSONField(default=list, verbose_name='Список задач'),
        ),
    ]
