# Generated by Django 5.0 on 2024-01-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_todolists_task_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolists',
            name='task_data',
        ),
    ]
