# Generated by Django 5.0 on 2024-01-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0010_remove_todolists_task_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todolists',
            new_name='todolist',
        ),
    ]
