# Generated by Django 5.0 on 2024-01-16 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0011_rename_todolists_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='nameOfList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_list', models.CharField(max_length=100, verbose_name='Название списка ваших дел: ')),
            ],
        ),
        migrations.AlterField(
            model_name='todolist',
            name='done_or_not',
            field=models.BooleanField(verbose_name='Сделано или нет: '),
        ),
        migrations.CreateModel(
            name='lists_of_todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_or_not', models.BooleanField(verbose_name='Сделано или нет: ')),
                ('name_of_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.nameoflist')),
            ],
        ),
    ]
