# Generated by Django 5.0 on 2024-01-16 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0012_nameoflist_alter_todolist_done_or_not_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='list_of_todolist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todolist.nameoflist'),
        ),
        migrations.DeleteModel(
            name='lists_of_todolist',
        ),
    ]
