# Generated by Django 5.0 on 2024-01-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0013_todolist_list_of_todolist_delete_lists_of_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='list_of_todolist',
        ),
        migrations.AddField(
            model_name='todolist',
            name='lists_of_todolist',
            field=models.ManyToManyField(related_name='tasks', to='todolist.nameoflist'),
        ),
    ]
