# Generated by Django 5.0 on 2024-01-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0014_remove_todolist_list_of_todolist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nameoflist',
            options={'verbose_name': 'Списки дел', 'verbose_name_plural': 'Списки дел'},
        ),
        migrations.AddField(
            model_name='todolist',
            name='date_field',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
