# Generated by Django 5.0 on 2024-01-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0015_alter_nameoflist_options_todolist_date_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='lists_of_todolist',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='todolist.nameoflist'),
        ),
    ]
